### ISSUE TITLE
Missing ')' after argument list

### ISSUE THREAD

**Issue by k-bx** [ellie-app/ellie#75] opened 2018-12-27 11:32 UTC
Weird error after trying to compile an example from https://raw.githubusercontent.com/mdgriffith/elm-style-animation/master/examples/SimpleFadeIn.elm

https://ellie-app.com/4h5SzQNXrz4a1

**Comment by tbash** [comment] 2018-12-27 17:30
This is due to Ellie compiling with `--debug` and is a known issue of the compiler in certain situations, this being one of them. 

An issue exists for the compiler here: https://github.com/elm/compiler/issues/1851

Another exists for a suggested temporary solution for elm-style-animation: https://github.com/mdgriffith/elm-style-animation/issues/67. 

Duplicate of https://github.com/ellie-app/ellie/issues/67

**Closed by tbash** 2018-12-27 17:30 UTC
