### ISSUE TITLE
Ellie app crashes for code that runs locally

### ISSUE THREAD

**Issue by jhf** [ellie-app/ellie#71] opened 2018-11-08 18:29 UTC
The following Ellie snippet [1], using elm-style-animation [2], crashes in Ellie when it's being run.
The error message is 

```
Exception Thrown in Output
ReferenceError: Can't find variable: Elm
```

However, when creating the same files locally, it compiles and runs correctly.
After some clarifications, I don't think that using elm-style-animation is important,
however, i think there is a bug in Ellie, because it should give a compilation error message,
if Elm fails to compile, or `Elm` should be defined in the javascript.

[1] https://ellie-app.com/3QfgN3mP6fva1
[2] https://package.elm-lang.org/packages/mdgriffith/elm-style-animation/4.0.0

**Comment by tbash** [comment] 2018-12-27 17:30
This is due to Ellie compiling with `--debug` and is a known issue of the compiler in certain situations, this being one of them. 

An issue exists for the compiler here: https://github.com/elm/compiler/issues/1851

Another exists for a suggested temporary solution for elm-style-animation: https://github.com/mdgriffith/elm-style-animation/issues/67. 

Duplicate of https://github.com/ellie-app/ellie/issues/67

**Closed by tbash** 2018-12-27 17:30 UTC
