### ISSUE TITLE
Exception Thrown in Output: Uncaught ReferenceError: Elm is not defined

### ISSUE THREAD

**Issue by n1k0** [ellie-app/ellie#99] opened 2019-07-12 06:55 UTC
Here's a SSCCE highlighting a strange bug in Ellie. I can't provide a link because the setup crashes with an `Exception Thrown in Output: Uncaught ReferenceError: Elm is not defined` error notification, so I can't save.

### Dependencies

- [allo-media/elm-daterange-picker](https://package.elm-lang.org/packages/allo-media/elm-daterange-picker/1.0.0/) (1.0.0)

### Elm code

```elm
module Main exposing (main)

import Browser
import DateRangePicker
import Html exposing (Html, text)

type Msg
    = PickerChanged DateRangePicker.State

main : Program () () Msg
main =
    Browser.sandbox
        { init = ()
        , view = always (text "ok")
        , update = always (always ()) 
        }
```

### Html code

```html
<html>
<head>
  <style>
    /* you can style your program here */
  </style>
</head>
<body>
  <main></main>
  <script>
    var app = Elm.Main.init({ node: document.querySelector("main") })
    // you can use ports and stuff here
  </script>
</body>
</html>
```

### Result

![](https://i.imgur.com/dYihPvM.png)

(notice the `Compiled succesfully` in the status bar)

### Comment

As you can see, simply defining a `Msg` member referencing the `DateRangePicker.State` type makes Ellie crash. If I change the `Msg` type to:

```elm
type Msg
    = Works
```

it compiles.

Also, if you bypass the `Browser.sandbox` setup entirely and just run:

```elm
module Main exposing (main)

import DateRangePicker
import Html exposing (Html, text)


type Msg
    = PickerChanged DateRangePicker.State


main : Html Msg
main =
    text "test"
```

It doesn't crash.

I don't have a clue what's happening, but I know the `DateRangePicker` package works fine in production and in it's own [demo app](https://github.com/allo-media/elm-daterange-picker/blob/master/demo/Main.elm).

**Comment by tbash** [comment] 2019-12-02 06:13
Duplicate of https://github.com/ellie-app/ellie/issues/112, https://github.com/ellie-app/ellie/issues/115, and a few others. Ultimately this is the root issue https://github.com/elm/compiler/issues/1851, it was fixed in the `0.19.1` release of Elm and will be fixed in the next release of Ellie. Thank you for taking the time to submit an issue!

**Closed by tbash** 2019-12-02 06:13 UTC
