### ISSUE TITLE
Does not work on Firefox

### ISSUE THREAD

**Issue by tgelu** [ellie-app/ellie#55] opened 2018-05-31 07:54 UTC
Am I alone in this issue? I had the impression I used Ellie with Firefox, but lately I get only a big logo with nothing happening and nothing logged.

**Comment by lukewestby** [comment] 2018-06-01 18:20
can you share your operating system and firefox version?

**Comment by tgelu** [comment] 2018-06-06 12:32
sure, should have done this earlier:
Firefox 60.0.1 (64-bit)
Windows 7 (64-bit) (old os due to this being a work machine)

**Comment by lukewestby** [comment] 2018-06-29 16:19
I can't reproduce any issues on Firefox 60 on Windows 7 so I'm gonna have to close this

**Closed by lukewestby** 2018-06-29 16:19 UTC

**Comment by tgelu** [comment] 2018-07-04 07:38
I cannot reproduce it either now. It works just fine.
I really hope it wasn't just very slow and I haven't noticed the loading state (since the nice shiny animation of the ellie logo doesn't work in firefox).

Any any case. Thanks for looking into this, great job with Ellie! :+1:
