### ISSUE TITLE
Ellie does not load in some regions

### ISSUE THREAD

**Issue by Drenmi** [ellie-app/ellie#87] opened 2019-03-14 02:23 UTC
There are numerous cases of ellie-app.com not loading for people who are not in the US or EU, or people using VPN. The editor simply gets stuck loading, with the WebSocket connection in a perpetual `pending` state. (See below.)

The common factor seems to be connecting from East Asia or other remote locations, or using a VPN that routes through one. Perhaps the channel connection times out too quickly on the server side?

<img width="562" alt="Screenshot 2019-03-14 at 10 16 58" src="https://user-images.githubusercontent.com/5259935/54326740-6bb01b00-4642-11e9-8c59-39cc07c54641.png">

**Examples from Slack:**

> I came here to say the exact same thing. I believe it has something to do with latency. The VPN I use is rather slow (transatlantic).

> Is it only me or recently Ellie often doesn't start? It usually stops at the logo. If I reload the page, then sometime it goes through. I am in Japan.

> Stuck on loading for me too. I've only noticed the problem while in South Africa.

**Comment by sentience** [comment] 2019-04-01 07:27
Indeed, Ellie not working for us here in Melbourne, Australia.

**Comment by tbash** [comment] 2019-04-03 03:10
Excitingly enough, I have found the issue. It is not directly related to latency is in fact due to a race condition revealed by latency. This explains why some are only able to recreate it sometimes while others can recreate all of the time. 

 This https://github.com/ellie-app/ellie/blob/master/lib/ellie_web/graphql/schema.ex#L87 is being published before the client is ready to receive it, adding `Process.sleep/1` for some amount of time to the line above gives it enough time to correct itself. This is not the solution that will go to production but is a point of interest. I will have a suitable fix for this in the next day or so.

I'm going to leave this issue open until I can confirm those currently having issues can use Ellie with none.

**Comment by tbash** [comment] 2019-04-05 06:46
Should be fixed w/https://github.com/ellie-app/ellie/pull/90

**Closed** 2019-04-11 20:43 UTC
Labels: bug
